version: "3.7"

services:
  app:
    build:
      context: ./Docker/php/8.0
    container_name: yampi_test_app
    image: somosyampi/php:8.0
    init: true
    volumes:
        - .:/app:delegated
    networks:
        - yampi

  nginx:
    build:
      context: ./Docker/nginx
    image: somosyampi/http
    ports:
        - 8000:80
    volumes:
        - .:/app:delegated
    environment:
      FPM_HOST: app
    networks:
        - yampi
    depends_on:
        - app

  redis:
    container_name: "yampi_test_redis"
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass secret
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
        - yampi

  mailhog:
      image: mailhog/mailhog
      logging:
        driver: 'none'  # disable saving logs
      ports:
        - 1025:1025 # smtp server
        - 8025:8025 # web ui
      volumes:
        - .:/app:delegated
      networks:
        - yampi
  db:
    image: mariadb:10.2
    container_name: yampi_test_db
    volumes:
        - ./mysql/data:/var/lib/mysql:${VOLUME_ATR:-delegated}
    restart: always
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: yampi
    networks:
        - yampi

networks:
  yampi:
    name: yampi
